defmodule AdventOfCode2024.Day5Test do
  use ExUnit.Case, async: true

  test "part_one/1" do
    input = """
    ....#.....
    .........#
    ..........
    ..#.......
    .......#..
    ..........
    .#..^.....
    ........#.
    #.........
    ......#...
    """

    assert AdventOfCode2024.Day5.part_one(input) == 41
  end

  test "part_two/1" do
    input = """
    ....#.....
    .........#
    ..........
    ..#.......
    .......#..
    ..........
    .#..^.....
    ........#.
    #.........
    ......#...
    """

    assert AdventOfCode2024.Day5.part_two(input) == 6
  end
end
