defmodule AdventOfCode2024.Day8Test do
  use ExUnit.Case, async: true

  test "part_one/1" do
    input = """
    ............
    ........0...
    .....0......
    .......0....
    ....0.......
    ......A.....
    ............
    ............
    ........A...
    .........A..
    ............
    ............
    """

    assert AdventOfCode2024.Day8.part_one(input) == 14
  end

  test "part_two/1" do
    input = """
    ............
    ........0...
    .....0......
    .......0....
    ....0.......
    ......A.....
    ............
    ............
    ........A...
    .........A..
    ............
    ............
    """

    assert AdventOfCode2024.Day8.part_two(input) == 34
  end
end
